const CartActionTypes = {
	TOGGLE_HIDDEN: 'TOGGLE_HIDDEN',
	ADD_ITEM: 'ADD_ITEM',
	REMOVE_ITEM: 'REMOVE_ITEM',
	CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
	CLEAR_CART: 'CLEAR_CART',
	PAYMENT_SUCCESSFUL: 'PAYMENT_SUCCESSFUL',
};

export default CartActionTypes;